blank_issues_enabled: false
contact_links:
  - name: Support exclusively on the wahltho Discord server
    url: https://discord.gg/ySS88PMuyC
    about: Installation questions, bug reports and feature requests. No official Zibo or LevelUp support.
