<Project><PropertyGroup><BaseOutputPath>/Users/wahltho/Documents/Projects/X-Plane-LevelUp-737NG-VREF/artifacts/mtk-e2e-build/bin/$(MSBuildProjectName)/</BaseOutputPath><BaseIntermediateOutputPath>/Users/wahltho/Documents/Projects/X-Plane-LevelUp-737NG-VREF/artifacts/mtk-e2e-build/obj/$(MSBuildProjectName)/</BaseIntermediateOutputPath></PropertyGroup></Project>
